version: "3.7"

services:
  zookeeper:
    # for kafka
    # https://www.hangge.com/blog/cache/detail_2791.html
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - "2181:2181"
    networks:
      - ProducerNetwork
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # Config https://blog.csdn.net/weixin_38399962/article/details/90057227
    # Enter the container; docker exec -it kafka /bin/bash
    # Check environment variable; docker exec <container_id> bash -c 'echo "$ENV_VAR"'
    # List topics; docker exec kafka kafka-topics.sh --list --zookeeper 192.168.60.133:2181
    # Producing; docker exec -it kafka kafka-console-producer.sh --broker-list 192.168.60.133:9092 --topic test
    # Consuming; docker exec -it kafka kafka-console-consumer.sh --bootstrap-server 192.168.60.133:9092 --topic test --from-beginning
    build: ./services/kafka
    ports:
      - "9092"
      - "9093"
      - "9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 720
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL_LISTENER:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT,DOCKER_SASL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LOCAL_LISTENER://localhost:9092,DOCKER_LISTENER://kafka:9093,DOCKER_SASL://kafka:9094
      KAFKA_LISTENERS: LOCAL_LISTENER://:9092,DOCKER_LISTENER://:9093,DOCKER_SASL://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENER
      ZOOKEEPER_SASL_ENABLED: 'FALSE'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/ssl/private/kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: PCTkafka
      KAFKA_SSL_KEYSTORE_LOCATION: /var/ssl/private/kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: PCTkafka
      KAFKA_SSL_KEY_PASSWORD: PCTkafka

      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'

    volumes:
      - ./services/kafka/truststore/kafka.truststore.jks:/var/ssl/private/kafka.server.truststore.jks
      - ./services/kafka/keystore/kafka.keystore.jks:/var/ssl/private/kafka.server.keystore.jks

    depends_on:
      - zookeeper
    networks:
      - ProducerNetwork

networks:
    ProducerNetwork:
      name: producernet
      driver: bridge

