version: "3.7"

services:
  zookeeper:
    # for kafka
    # https://www.hangge.com/blog/cache/detail_2791.html
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - "2181:2181"
    networks:
      - ProducerNetwork
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # Config https://blog.csdn.net/weixin_38399962/article/details/90057227
    # Enter the container; docker exec -it kafka /bin/bash
    # Check environment variable; docker exec <container_id> bash -c 'echo "$ENV_VAR"'
    # List topics; docker exec kafka kafka-topics.sh --list --zookeeper 192.168.60.133:2181
    # Producing; docker exec -it kafka kafka-console-producer.sh --broker-list 192.168.60.133:9092 --topic test
    # Consuming; docker exec -it kafka kafka-console-consumer.sh --bootstrap-server 192.168.60.133:9092 --topic test --from-beginning
    build: ./services/kafka
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER1:PLAINTEXT,LISTENER2:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS:LISTENER1://kafka:9092,LISTENER2://kafka:9093
      #KAFKA_LISTENERS:LISTENER1://:9092,LISTENER2://kafka:9093
      #KAFKA_OPTS:'-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #ZOOKEEPER_SASL_ENABLED:'FALSE'
      #KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER1
    depends_on:
      - zookeeper
    networks:
      - ProducerNetwork

networks:
    ProducerNetwork:
      name: producernet
      driver: bridge

